2. [28 points] We will first implement SVM in the primal domain with stochastic subgradient descent. We will reuse the dataset for Perceptron implementation, namely, “bank-note.zip” in Canvas. The features and labels are listed in the file “classification/data-desc.txt”. The training data are stored in the file “classification/train.csv”, consisting of 872 examples. The test data are stored in “classification/test.csv”, and comprise of 500 examples. In both the training and test datasets, feature values and labels are separated by commas. Set the maximum epochs T to 100. Don’t forget to shuffle the training examples at the start of each epoch. Use the curve of the objective function (along with the number of updates) to diagnosis the convergence. Try the hyperparameter C from {100/873, 500/873, 700/873}. Don’t forget to convert the labels to be in {1,−1}.


In [1]:
import pandas as pd
from svm import SVM
import numpy as np
import matplotlib.pyplot as plt

X_training = np.genfromtxt('../data/bank-note/train.csv', delimiter=',')
X_test = np.genfromtxt('../data/bank-note/test.csv', delimiter=',')

y_training = X_training[:, -1]
y_test = X_test[:, -1]

y_training[y_training == 0] = -1
y_test[y_test == 0] = -1

X_training = np.insert(X_training, 0, 1, axis=1)
X_test = np.insert(X_test, 0, 1, axis=1)

X_training = X_training[:, :-1]
X_test = X_test[:, :-1]



(a) [12 points] Use the schedule of learning rate: γt = γ0 / 1+(γ0/a) * t. Please tune γ0 > 0 and
a > 0 to ensure convergence. For each setting of C, report your training and test error.


In [13]:
C = [100/873, 500/873, 700/873]
epoch = 100
r = 0.01
a = 0.01
default_schedule = True
train_errors_1 = []
test_errors_1 = []
models_1 = []

for i in range(len(C)):
    svm = SVM(variant='primal', C=C[i], epoch=epoch, r=r, a=a, default_schedule=default_schedule)
    svm.fit(X_training, y_training)
    train_pred_1 = svm.predict(X_training)
    test_pred_1 = svm.predict(X_test)
    train_error_1 = np.sum(train_pred_1 != y_training) / len(y_training)
    test_error_1 = np.sum(test_pred_1 != y_test) / len(y_test)
    train_errors_1.append(train_error_1)
    test_errors_1.append(test_error_1)
    models_1.append(svm.get_model())

    print('C: ', C[i])
    print('Training error: ', train_error_1)
    print('Test error: ', test_error_1)

C:  0.1145475372279496
Training error:  0.033256880733944956
Test error:  0.04
C:  0.572737686139748
Training error:  0.034403669724770644
Test error:  0.036
C:  0.8018327605956472
Training error:  0.01834862385321101
Test error:  0.024


(b) [12 points] Use the schedule γt = γ0 / 1+t. Report the training and test error for each
setting of C.


In [18]:
C = [100/873, 500/873, 700/873]
epoch = 100
r = 0.01
a = 0.01
default_schedule = False
train_errors_2 = []
test_errors_2 = []
models_2 = []

for i in range(len(C)):
    svm = SVM(variant='primal', C=C[i], epoch=epoch, r=r, a=a, default_schedule=default_schedule)
    svm.fit(X_training, y_training)
    train_pred_2 = svm.predict(X_training)
    test_pred_2 = svm.predict(X_test)
    train_error_2 = np.sum(train_pred_2 != y_training) / len(y_training)
    test_error_2 = np.sum(test_pred_2 != y_test) / len(y_test)
    train_errors_2.append(train_error_2)
    test_errors_2.append(test_error_2)
    models_2.append(svm.get_model())

    print('C: ', C[i])
    print('Training error: ', train_error_2)
    print('Test error: ', test_error_2)

C:  0.1145475372279496
Training error:  0.0963302752293578
Test error:  0.11
C:  0.572737686139748
Training error:  0.04128440366972477
Test error:  0.034
C:  0.8018327605956472
Training error:  0.04128440366972477
Test error:  0.034


(c) [6 points] For each C, report the differences between the model parameters learned
from the two learning rate schedules, as well as the differences between the train-
ing/test errors. What can you conclude?

In [11]:
print('Difference in training error between default and non-default schedule: ')
for i in range(len(C)):
    print('C: ', C[i])
    print(np.abs(train_errors_1[i] - train_errors_2[i]))
print('\n')

# print(np.abs(np.array(train_errors_1) - np.array(train_errors_2)), '\n')
print('Difference in test error between default and non-default schedule: ')
for i in range(len(C)):
    print('C: ', C[i])
    print(np.abs(test_errors_1[i] - test_errors_2[i]))
print('\n')

print('Difference in models between default and non-default schedule: ')
for i in range(len(C)):
    print('C: ', C[i])
    print(np.abs(models_1[i] - models_2[i]))

print('\n')
print('Models for default schedule: ')
for i in range(len(models_1)):
    print(models_1[i])
print('Models for non-default schedule: ')
for i in range(len(models_2)):
    print(models_2[i])

Difference in training error between default and non-default schedule: 
C:  0.1145475372279496
0.04357798165137614
C:  0.572737686139748
0.009174311926605505
C:  0.8018327605956472
0.0022935779816513763


Difference in test error between default and non-default schedule: 
C:  0.1145475372279496
0.036
C:  0.572737686139748
0.0020000000000000018
C:  0.8018327605956472
0.013999999999999999


Difference in models between default and non-default schedule: 
C:  0.1145475372279496
[0.09988545 0.52658672 0.81622496 1.20032015 0.35963174]
C:  0.572737686139748
[0.         1.50031196 0.31420218 3.5837427  0.32286674]
C:  0.8018327605956472
[0.         1.73442643 0.69604478 6.54326985 7.14443554]


Models for default schedule: 
[ 2.99656357 -3.24264552 -1.88218553 -2.97874167 -0.98903095]
[ 10.98739977 -14.60346041 -10.82765047  -8.89138346  -3.93749752]
[ 16.08155785 -19.3894399  -13.95640795 -10.37500306  -1.64404283]
Models for non-default schedule: 
[ 3.09644903 -3.76923224 -2.69841049 -1.778

3. [30 points] Now let us implement SVM in the dual domain. We use the same dataset, “bank-note.zip”. You can utilize existing constrained optimization libraries. For Python, we recommend using “scipy.optimize.minimize”, and you can learn how to use this API from the document at https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.optimize.minimize.html. We recommend using SLSQP to incorporate the equality constraints. For Matlab, we recommend using the internal function “fmincon”; the document and examples are given at https://www.mathworks.com/help/optim/ug/fmincon.html. For R, we recommend using the “nloptr” package with detailed documentation at https://cran.r-project.org/web/packages/nloptr/nloptr.pdf.


(a) [10 points] First, run your dual SVM learning algorithm with C in {100 / 873, 500 / 873, 700 /873}. Recover the feature weights w and the bias b. Compare with the parameters learned with stochastic sub-gradient descent in the primal domain (in Problem 2) and the same settings of C, what can you observe? What do you conclude and why? Note that if your code calculates the objective function with a double loop, the optimization can be quite slow. To accelerate, consider writing down the objective in terms of the matrix and vector operations, and treat the Lagrange
multipliers that we want to optimize as a vector! Recall, we have discussed about it in our class

In [2]:
import pandas as pd
from svm import SVM
import numpy as np

X_training = np.genfromtxt('../data/bank-note/train.csv', delimiter=',')
X_test = np.genfromtxt('../data/bank-note/test.csv', delimiter=',')
y_training = X_training[:, -1]
y_test = X_test[:, -1]
y_training[y_training == 0] = -1
y_test[y_test == 0] = -1

# X_training = np.insert(X_training, 0, 1, axis=1)
# X_test = np.insert(X_test, 0, 1, axis=1)

X_training = X_training[:, :-1]
X_test = X_test[:, :-1]



C_dual = [100/873, 500/873, 700/873]

dual_train_errors_1 = []
dual_test_errors_1 = []
dual_models_1 = []

for i in range(len(C_dual)):
    svm_dual = SVM(variant='dual', C=C_dual[i])
    svm_dual.fit(X_training, y_training)
    print(svm_dual.get_model())

    d_train_pred_1 = svm_dual.predict(X_training)
    d_test_pred_1 = svm_dual.predict(X_test)

    d_train_error_1 = np.sum(d_train_pred_1 != y_training) / len(y_training)
    d_test_error_1 = np.sum(d_test_pred_1 != y_test) / len(y_test)

    dual_train_errors_1.append(d_train_error_1)
    dual_test_errors_1.append(d_test_error_1)

    dual_models_1.append(svm_dual.get_model())

    print('C: ', C_dual[i])
    print('Training error: ', d_train_error_1)
    print('Test error: ', d_test_error_1)
    print('\n')

[ 2.51728438 -0.94292749 -0.65149165 -0.73372163 -0.0410216 ]
C:  0.1145475372279496
Training error:  0.026376146788990827
Test error:  0.03


[ 3.96538542 -1.56393877 -1.01405238 -1.18065128 -0.15651755]
C:  0.572737686139748
Training error:  0.03096330275229358
Test error:  0.036


[ 5.0371374  -2.04255067 -1.28070426 -1.51352641 -0.24906657]
C:  0.8018327605956472
Training error:  0.034403669724770644
Test error:  0.036




(b) [15 points] Now, use Gaussian kernel in the dual form to implement the non-
linear SVM. Note that you need to modify both the objective function and the
prediction. The Gaussian kernel is defined as follows:
k(xi,xj) = exp(−‖xi −xj‖^2 / γ ). Test γ from {0.1,0.5,1,5,100} and the hyperparameter C from {100/
873, 500/873, 700/873}. List the training and test errors for the combinations of all the γ and C values. What is the best combination? Compared with linear SVM with the same settings of C, what do you observe? What do you conclude and why?

In [10]:
import pandas as pd
from svm import SVM
import numpy as np
import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)

X_training = np.genfromtxt('../data/bank-note/train.csv', delimiter=',')
X_test = np.genfromtxt('../data/bank-note/test.csv', delimiter=',')
y_training = X_training[:, -1]
y_test = X_test[:, -1]
y_training[y_training == 0] = -1
y_test[y_test == 0] = -1

# X_training = np.insert(X_training, 0, 1, axis=1)
# X_test = np.insert(X_test, 0, 1, axis=1)

X_training = X_training[:, :-1]
X_test = X_test[:, :-1]

C = [100/873, 500/873, 700/873] # regularization parameter
r = [0.1, 0.5, 1, 5, 100]

dual_train_errors_2 = []
dual_test_errors_2 = []
dual_models_2 = []

for i in range(len(C)):
    for j in range(len(r)):
        svm_dual = SVM(variant='dual', C=C[i], r=r[j], kernel='gaussian')
        svm_dual.fit(X_training, y_training)

        d_train_pred_2 = svm_dual.predict(X_training)
        d_test_pred_2 = svm_dual.predict(X_test)

        d_train_error_2 = np.sum(d_train_pred_2 != y_training) / len(y_training)
        d_test_error_2 = np.sum(d_test_pred_2 != y_test) / len(y_test)

        dual_train_errors_2.append(d_train_error_2)
        dual_test_errors_2.append(d_test_error_2)

        print('C: ', C[i], 'r: ', r[j])
        print('Training error: ', d_train_error_2)
        print('Test error: ', d_test_error_2)
        print('\n')

C:  0.1145475372279496 r:  0.1
Training error:  0.04128440366972477
Test error:  0.39


C:  0.1145475372279496 r:  0.5
Training error:  0.010321100917431193
Test error:  0.118


C:  0.1145475372279496 r:  1
Training error:  0.0
Test error:  0.02


C:  0.1145475372279496 r:  5
Training error:  0.0
Test error:  0.0


C:  0.1145475372279496 r:  100
Training error:  0.021788990825688075
Test error:  0.022


C:  0.572737686139748 r:  0.1
Training error:  0.0
Test error:  0.2


C:  0.572737686139748 r:  0.5
Training error:  0.0
Test error:  0.012


C:  0.572737686139748 r:  1
Training error:  0.0
Test error:  0.004


C:  0.572737686139748 r:  5
Training error:  0.0
Test error:  0.004


C:  0.572737686139748 r:  100
Training error:  0.010321100917431193
Test error:  0.012


C:  0.8018327605956472 r:  0.1
Training error:  0.0
Test error:  0.18


C:  0.8018327605956472 r:  0.5
Training error:  0.0
Test error:  0.01


C:  0.8018327605956472 r:  1
Training error:  0.0
Test error:  0.004


C:  0.8

(c) [5 points] Following (b), for each setting of γ and C, list the number of support
vectors. When C = 500/873, report the number of overlapped support vectors between consecutive values of γ, i.e., how many support vectors are the same for γ = 0.01 and γ = 0.1; how many are the same for γ = 0.1 and γ = 0.5, etc. What do you observe and conclude? Why?